# Data Cleaning Process for Google Data Analytics Capstone Project Case Study-I Cyclistic

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import datetime

### We load the dataset into a datframe using the pandas library in python

In [2]:
df=pd.read_csv("D:\datset_cap\cyclistic.csv",low_memory=False)
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152,41.8964,-87.6610,41.9322,-87.6586,member
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499,41.9244,-87.7154,41.9306,-87.7238,member
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255,41.8945,-87.6179,41.8679,-87.6230,member
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657,41.9030,-87.6975,41.8992,-87.6722,member
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323,41.8902,-87.6262,41.9695,-87.6547,casual

In [3]:
df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

### We observe that the dates are of type object and thus we convert them(this is because the python interpreter automatically assigns a type)

In [4]:
df["started_at"] = pd.to_datetime(df["started_at"])
df["ended_at"] = pd.to_datetime(df["ended_at"])

In [5]:
df["distance"]= df["ended_at"] - df["started_at"]
df["distance"]
#ride_length is distance

0         0 days 00:26:49
1         0 days 00:08:09
2         0 days 00:14:23
3         0 days 00:12:12
4         0 days 00:52:55
                ...
3541678   0 days 00:00:01
3541679   0 days 00:48:08
3541680   0 days 00:25:51
3541681   0 days 00:10:33
3541682   0 days 00:28:30
Name: distance, Length: 3541683, dtype: timedelta64[ns]

#### Split the date time column which has a delimiter (space) and get the individual date and time for easier calculation down the line

In [6]:
df[['start_date','start_time']] = df['started_at'].astype(str).str.split(' ',n=1,expand=True)

In [10]:
df["start_time"] = pd.to_datetime(df["start_time"])
df["start_date"] = pd.to_datetime(df["start_date"])

#### We seperate the year and month for checking for incoonsistent data and further for analysis

In [11]:
df['start_year'] = pd.DatetimeIndex(df['start_date']).year
df['start_month']= pd.DatetimeIndex(df['start_date']).month
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,distance,start_date,start_time,start_year,start_month
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152,41.8964,-87.6610,41.9322,-87.6586,member,0 days 00:26:49,2020-04-26,2022-05-24 17:45:14,2020,4
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499,41.9244,-87.7154,41.9306,-87.7238,member,0 days 00:08:09,2020-04-17,2022-05-24 17:08:54,2020,4
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255,41.8945,-87.6179,41.8679,-87.6230,member,0 days 00:14:23,2020-04-01,2022-05-24 17:54:13,2020,4
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657,41.9030,-87.6975,41.8992,-87.6722,member,0 days 00:12:12,2020-04-07,2022-05-24 12:50:19,2020,4
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323,41.8902,-87.6262,41.9695,-87.6547,casual,0 days 00:52:55,2020-04-18,2022-05-24 10:22:59,2020,4

In [12]:
df[['end_date','end_time']] = df['ended_at'].astype(str).str.split(' ',n=1,expand=True)

In [15]:
df["end_time"] = pd.to_datetime(df["end_time"])
df["end_date"] = pd.to_datetime(df["end_date"])

In [17]:
df.head()
df["time_diff"]=df["end_time"]-df["start_time"]

#### Calculate the difference between the start and end times and days

In [18]:
df["time_diff"]=df["end_time"]-df["start_time"]

In [19]:
df["day_diff"]=df["end_date"]-df["start_date"]

In [20]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,distance,start_date,start_time,start_year,start_month,end_date,end_time,time_diff,day_diff
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152,41.8964,-87.6610,...,member,0 days 00:26:49,2020-04-26,2022-05-24 17:45:14,2020,4,2020-04-26,2022-05-24 18:12:03,0 days 00:26:49,0 days
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499,41.9244,-87.7154,...,member,0 days 00:08:09,2020-04-17,2022-05-24 17:08:54,2020,4,2020-04-17,2022-05-24 17:17:03,0 days 00:08:09,0 days
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255,41.8945,-87.6179,...,member,0 days 00:14:23,2020-04-01,2022-05-24 17:54:13,2020,4,2020-04-01,2022-05-24 18:08:36,0 days 00:14:23,0 days
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657,41.9030,-87.6975,...,member,0 days 00:12:12,2020-04-07,2022-05-24 12:50:19,2020,4,2020-04-07,2022-05-24 13:02:31,0 days 00:12:12,0 days
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323,41.8902,-87.6262,...,casual,0 days 00:52:55,2020-04-18,2022-05-24 10:22:59,2020,4,2020-04-18,2022-05-24 11:15:54,0 days 00:52:55,0 days

#### We sort in ascending order to see if there are any outliers in the given dataset

In [21]:
df.sort_values(by=["day_diff"],ascending=True)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,distance,start_date,start_time,year,month,end_date,end_time,time_diff,day_diff
2986843,52C655580214D2EF,docked_bike,2020-12-15 12:05:19,2020-11-25 19:03:00,Milwaukee Ave & Wabansia Ave,13243,Wood St & Chicago Ave,637,41.912616,-87.681391,...,member,-20 days +06:57:41,2020-12-15,2022-05-22 12:05:19,2020,12,2020-11-25,2022-05-22 19:03:00,0 days 06:57:41,-20 days
3049544,FB3820447AF11432,electric_bike,2020-12-15 12:12:46,2020-11-25 22:23:03,NaN,NaN,Wolcott Ave & Fargo Ave,519,41.990000,-87.660000,...,casual,-20 days +10:10:17,2020-12-15,2022-05-22 12:12:46,2020,12,2020-11-25,2022-05-22 22:23:03,0 days 10:10:17,-20 days
3005689,18B3779B78871E64,docked_bike,2020-12-15 11:44:37,2020-11-25 12:26:04,Winthrop Ave & Lawrence Ave,TA1308000021,Cannon Dr & Fullerton Ave,13124,41.968812,-87.657659,...,member,-20 days +00:41:27,2020-12-15,2022-05-22 11:44:37,2020,12,2020-11-25,2022-05-22 12:26:04,0 days 00:41:27,-20 days
3065420,F4BE3879DC27EAFF,electric_bike,2020-12-15 12:03:43,2020-11-25 18:18:09,Clark St & Winnemac Ave,TA1309000035,Broadway & Waveland Ave,13325,41.973371,-87.667869,...,member,-20 days +06:14:26,2020-12-15,2022-05-22 12:03:43,2020,12,2020-11-25,2022-05-22 18:18:09,0 days 06:14:26,-20 days
3080196,165F7B547D1CFAC0,docked_bike,2020-12-15 12:21:50,2020-11-25 19:24:03,Clark St & Elm St,TA1307000039,Fairbanks Ct & Grand Ave,TA1305000003,41.902973,-87.631280,...,member,-20 days +07:02:13,2020-12-15,2022-05-22 12:21:50,2020,12,2020-11-25,2022-05-22 19:24:03,0 days 07:02:13,-20 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3220034,63F1D0FB38E8B158,docked_bike,2020-01-26 10:24:05,2020-03-28 22:15:51,Ellis Ave & 53rd St,418,Cottage Grove Ave & 47th St,336,41.799300,-87.601000,...,casual,62 days 11:51:46,2020-01-26,2022-05-22 10:24:05,2020,1,2020-03-28,2022-05-22 22:15:51,0 days 11:51:46,62 days
3475321,F4555B8C917E55D3,docked_bike,2020-03-02 17:57:47,2020-05-06 21:11:18,Halsted St & 63rd St,388,Calumet Ave & 33rd St,149,41.779400,-87.644600,...,member,65 days 03:13:31,2020-03-02,2022-05-22 17:57:47,2020,3,2020-05-06,2022-05-22 21:11:18,0 days 03:13:31,65 days
3274990,ABA59A8FED82A85C,docked_bike,2020-02-28 08:47:09,2020-05-19 20:10:34,Oakley Ave & Touhy Ave,526,Clark St & Schreiber Ave,453,42.012300,-87.688200,...,casual,81 days 11:23:25,2020-02-28,2022-05-22 08:47:09,2020,2,2020-05-19,2022-05-22 20:10:34,0 days 11:23:25,81 days
3376091,377B59F0A27BB4CB,docked_bike,2020-02-02 17:18:57,2020-05-12 16:15:42,Drake Ave & Fullerton Ave,503,Noble St & Milwaukee Ave,29,41.924400,-87.715400,...,casual,99 days 22:56:45,2020-02-02,2022-05-22 17:18:57,2020,2,2020-05-12,2022-05-22 16:15:42,-1 days +22:56:45,100 days
3171191,279F7DB076FD4444,docked_bike,2020-01-09 21:00:22,2020-04-27 12:30:46,Stony Island Ave & 75th St,270,South Shore Dr & 67th St,355,41.758700,-87.586900,...,casual,108 days 15:30:24,2020-01-09,2022-05-22 21:00:22,2020,1,2020-04-27,2022-05-22 12:30:46,-1 days +15:30:24,109 days

#### We see that there are a few entries with duration -20 days. We can clearly note that the data is inconsistent and thus needs to be removed so that the analysis is biased over untrue data

In [21]:
from datetime import datetime, timedelta
df = df[df['day_diff'] >= pd.Timedelta(0)]

In [22]:
df.sort_values(by=["day_diff"],ascending=True)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,distance,start_date,start_time,start_year,start_month,end_date,end_time,time_diff,day_diff
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152,41.896400,-87.661000,...,member,0 days 00:26:49,2020-04-26,2022-05-24 17:45:14,2020,4,2020-04-26,2022-05-24 18:12:03,0 days 00:26:49,0 days
2359616,06DDABF197960DDD,electric_bike,2020-10-10 20:22:27,2020-10-10 20:23:12,NaN,NaN,NaN,NaN,41.920000,-87.680000,...,casual,0 days 00:00:45,2020-10-10,2022-05-24 20:22:27,2020,10,2020-10-10,2022-05-24 20:23:12,0 days 00:00:45,0 days
2359617,42A1D98F8ADBE40A,electric_bike,2020-10-11 18:27:27,2020-10-11 18:35:04,Leavitt St & North Ave,213,California Ave & Francis Pl (Temp),259,41.910111,-87.682284,...,casual,0 days 00:07:37,2020-10-11,2022-05-24 18:27:27,2020,10,2020-10-11,2022-05-24 18:35:04,0 days 00:07:37,0 days
2359618,1DE457D8BF9158ED,electric_bike,2020-10-10 23:05:33,2020-10-10 23:15:51,NaN,NaN,NaN,NaN,41.950000,-87.700000,...,casual,0 days 00:10:18,2020-10-10,2022-05-24 23:05:33,2020,10,2020-10-10,2022-05-24 23:15:51,0 days 00:10:18,0 days
2359619,4200C28C9E58EE6E,electric_bike,2020-10-11 00:48:17,2020-10-11 01:00:27,NaN,NaN,Wells St & Huron St,53,41.930000,-87.650000,...,casual,0 days 00:12:10,2020-10-11,2022-05-24 00:48:17,2020,10,2020-10-11,2022-05-24 01:00:27,0 days 00:12:10,0 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3220034,63F1D0FB38E8B158,docked_bike,2020-01-26 10:24:05,2020-03-28 22:15:51,Ellis Ave & 53rd St,418,Cottage Grove Ave & 47th St,336,41.799300,-87.601000,...,casual,62 days 11:51:46,2020-01-26,2022-05-24 10:24:05,2020,1,2020-03-28,2022-05-24 22:15:51,0 days 11:51:46,62 days
3475321,F4555B8C917E55D3,docked_bike,2020-03-02 17:57:47,2020-05-06 21:11:18,Halsted St & 63rd St,388,Calumet Ave & 33rd St,149,41.779400,-87.644600,...,member,65 days 03:13:31,2020-03-02,2022-05-24 17:57:47,2020,3,2020-05-06,2022-05-24 21:11:18,0 days 03:13:31,65 days
3274990,ABA59A8FED82A85C,docked_bike,2020-02-28 08:47:09,2020-05-19 20:10:34,Oakley Ave & Touhy Ave,526,Clark St & Schreiber Ave,453,42.012300,-87.688200,...,casual,81 days 11:23:25,2020-02-28,2022-05-24 08:47:09,2020,2,2020-05-19,2022-05-24 20:10:34,0 days 11:23:25,81 days
3376091,377B59F0A27BB4CB,docked_bike,2020-02-02 17:18:57,2020-05-12 16:15:42,Drake Ave & Fullerton Ave,503,Noble St & Milwaukee Ave,29,41.924400,-87.715400,...,casual,99 days 22:56:45,2020-02-02,2022-05-24 17:18:57,2020,2,2020-05-12,2022-05-24 16:15:42,-1 days +22:56:45,100 days
3171191,279F7DB076FD4444,docked_bike,2020-01-09 21:00:22,2020-04-27 12:30:46,Stony Island Ave & 75th St,270,South Shore Dr & 67th St,355,41.758700,-87.586900,...,casual,108 days 15:30:24,2020-01-09,2022-05-24 21:00:22,2020,1,2020-04-27,2022-05-24 12:30:46,-1 days +15:30:24,109 days

#### We now see that after removing all the data with negative ride days time the least ride time is zero days. Continuing logically if there is flawed data relating to days it is worth checking out the intra day difference too!!

In [23]:
df.sort_values(by=["time_diff"],ascending=True)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,distance,start_date,start_time,start_year,start_month,end_date,end_time,time_diff,day_diff
2992767,CB931AD0518CE31F,electric_bike,2020-12-22 23:59:20,2020-12-23 00:00:18,NaN,NaN,NaN,NaN,41.800000,-87.600000,...,member,0 days 00:00:58,2020-12-22,2022-05-24 23:59:20,2020,12,2020-12-23,2022-05-24 00:00:18,-1 days +00:00:58,1 days
809780,CA42D0DD04455348,docked_bike,2020-07-17 23:58:45,2020-07-18 00:00:05,Mies van der Rohe Way & Chestnut St,145,Mies van der Rohe Way & Chicago Ave,173,41.898587,-87.621915,...,member,0 days 00:01:20,2020-07-17,2022-05-24 23:58:45,2020,7,2020-07-18,2022-05-24 00:00:05,-1 days +00:01:20,1 days
1324010,BA1F9C759CA4E515,docked_bike,2020-08-08 23:59:49,2020-08-09 00:01:09,Clark St & Lincoln Ave,141,Clark St & Lincoln Ave,141,41.915689,-87.634600,...,casual,0 days 00:01:20,2020-08-08,2022-05-24 23:59:49,2020,8,2020-08-09,2022-05-24 00:01:09,-1 days +00:01:20,1 days
2729019,018E566313573E82,electric_bike,2020-11-20 23:58:49,2020-11-21 00:00:09,NaN,NaN,NaN,NaN,41.910000,-87.720000,...,casual,0 days 00:01:20,2020-11-20,2022-05-24 23:58:49,2020,11,2020-11-21,2022-05-24 00:00:09,-1 days +00:01:20,1 days
3529718,1A95E83F6F31B201,docked_bike,2020-03-03 23:59:43,2020-03-04 00:01:12,State St & Van Buren St,33,Michigan Ave & Ida B Wells Dr,45,41.877200,-87.627800,...,member,0 days 00:01:29,2020-03-03,2022-05-24 23:59:43,2020,3,2020-03-04,2022-05-24 00:01:12,-1 days +00:01:29,1 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1574754,EA7286BEC37A6D0C,docked_bike,2020-08-07 00:22:20,2020-08-07 22:07:04,Lake Shore Dr & Ohio St,99,Clark St & Lake St,38,41.892570,-87.614492,...,casual,0 days 21:44:44,2020-08-07,2022-05-24 00:22:20,2020,8,2020-08-07,2022-05-24 22:07:04,0 days 21:44:44,0 days
708004,3F5819E5BE28BE1B,docked_bike,2020-07-18 00:20:52,2020-07-23 22:43:06,Racine Ave & 13th St,136,Wabash Ave & Adams St,39,41.865054,-87.656959,...,casual,5 days 22:22:14,2020-07-18,2022-05-24 00:20:52,2020,7,2020-07-23,2022-05-24 22:43:06,0 days 22:22:14,5 days
761936,3D36BF53098B7B01,docked_bike,2020-07-13 01:15:27,2020-07-13 23:38:12,Broadway & Belmont Ave,296,Broadway & Belmont Ave,296,41.940106,-87.645451,...,casual,0 days 22:22:45,2020-07-13,2022-05-24 01:15:27,2020,7,2020-07-13,2022-05-24 23:38:12,0 days 22:22:45,0 days
1577760,E7816CC5A78ED20E,docked_bike,2020-08-04 00:06:08,2020-08-04 22:30:31,Kedzie Ave & Leland Ave,476,Christiana Ave & Lawrence Ave,474,41.966686,-87.708052,...,casual,0 days 22:24:23,2020-08-04,2022-05-24 00:06:08,2020,8,2020-08-04,2022-05-24 22:30:31,0 days 22:24:23,0 days
1114139,5FFA1DCAE4390D00,docked_bike,2020-07-15 00:12:09,2020-07-15 23:08:40,McClurg Ct & Erie St,142,Ritchie Ct & Banks St,180,41.894503,-87.617854,...,casual,0 days 22:56:31,2020-07-15,2022-05-24 00:12:09,2020,7,2020-07-15,2022-05-24 23:08:40,0 days 22:56:31,0 days

#### As our suspicion suggested there are negative time differences within a day too which cannot be possible and thus we need to remove the outliers

In [24]:
df = df[df['time_diff'] >= pd.Timedelta(0)]

In [25]:
df.sort_values(by=["time_diff"],ascending=True)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,distance,start_date,start_time,start_year,start_month,end_date,end_time,time_diff,day_diff
3499226,46DC8E9D069A37F1,docked_bike,2020-03-09 12:23:15,2020-03-09 12:23:15,HQ QR,675,HQ QR,675,41.889900,-87.680300,...,casual,0 days 00:00:00,2020-03-09,2022-05-24 12:23:15,2020,3,2020-03-09,2022-05-24 12:23:15,0 days 00:00:00,0 days
1377808,6FEF1C606C469EA4,docked_bike,2020-08-18 14:03:56,2020-08-18 14:03:56,Damen Ave & Thomas St (Augusta Blvd),183,Damen Ave & Thomas St (Augusta Blvd),183,41.901315,-87.677409,...,member,0 days 00:00:00,2020-08-18,2022-05-24 14:03:56,2020,8,2020-08-18,2022-05-24 14:03:56,0 days 00:00:00,0 days
1721130,4FD3DD53CC8D8849,docked_bike,2020-08-21 18:03:36,2020-08-21 18:03:36,Cannon Dr & Fullerton Ave,34,Wilton Ave & Belmont Ave,117,41.926755,-87.634428,...,member,0 days 00:00:00,2020-08-21,2022-05-24 18:03:36,2020,8,2020-08-21,2022-05-24 18:03:36,0 days 00:00:00,0 days
2164359,CD6EF5E158F9CE53,docked_bike,2020-09-12 21:13:25,2020-09-12 21:13:25,Southport Ave & Wellington Ave,153,NaN,NaN,41.935733,-87.663576,...,member,0 days 00:00:00,2020-09-12,2022-05-24 21:13:25,2020,9,2020-09-12,2022-05-24 21:13:25,0 days 00:00:00,0 days
2249351,0F58DE4F00B6CBDA,docked_bike,2020-09-29 11:58:37,2020-09-29 11:58:37,Prairie Ave & 43rd St,410,NaN,NaN,41.816658,-87.619412,...,member,0 days 00:00:00,2020-09-29,2022-05-24 11:58:37,2020,9,2020-09-29,2022-05-24 11:58:37,0 days 00:00:00,0 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1574754,EA7286BEC37A6D0C,docked_bike,2020-08-07 00:22:20,2020-08-07 22:07:04,Lake Shore Dr & Ohio St,99,Clark St & Lake St,38,41.892570,-87.614492,...,casual,0 days 21:44:44,2020-08-07,2022-05-24 00:22:20,2020,8,2020-08-07,2022-05-24 22:07:04,0 days 21:44:44,0 days
708004,3F5819E5BE28BE1B,docked_bike,2020-07-18 00:20:52,2020-07-23 22:43:06,Racine Ave & 13th St,136,Wabash Ave & Adams St,39,41.865054,-87.656959,...,casual,5 days 22:22:14,2020-07-18,2022-05-24 00:20:52,2020,7,2020-07-23,2022-05-24 22:43:06,0 days 22:22:14,5 days
761936,3D36BF53098B7B01,docked_bike,2020-07-13 01:15:27,2020-07-13 23:38:12,Broadway & Belmont Ave,296,Broadway & Belmont Ave,296,41.940106,-87.645451,...,casual,0 days 22:22:45,2020-07-13,2022-05-24 01:15:27,2020,7,2020-07-13,2022-05-24 23:38:12,0 days 22:22:45,0 days
1577760,E7816CC5A78ED20E,docked_bike,2020-08-04 00:06:08,2020-08-04 22:30:31,Kedzie Ave & Leland Ave,476,Christiana Ave & Lawrence Ave,474,41.966686,-87.708052,...,casual,0 days 22:24:23,2020-08-04,2022-05-24 00:06:08,2020,8,2020-08-04,2022-05-24 22:30:31,0 days 22:24:23,0 days
1114139,5FFA1DCAE4390D00,docked_bike,2020-07-15 00:12:09,2020-07-15 23:08:40,McClurg Ct & Erie St,142,Ritchie Ct & Banks St,180,41.894503,-87.617854,...,casual,0 days 22:56:31,2020-07-15,2022-05-24 00:12:09,2020,7,2020-07-15,2022-05-24 23:08:40,0 days 22:56:31,0 days

In [26]:
df['end_year'] = pd.DatetimeIndex(df['end_date']).year
df['end_month']= pd.DatetimeIndex(df['end_date']).month
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,start_date,start_time,start_year,start_month,end_date,end_time,time_diff,day_diff,end_year,end_month
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152,41.8964,-87.6610,...,2020-04-26,2022-05-24 17:45:14,2020,4,2020-04-26,2022-05-24 18:12:03,0 days 00:26:49,0 days,2020,4
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499,41.9244,-87.7154,...,2020-04-17,2022-05-24 17:08:54,2020,4,2020-04-17,2022-05-24 17:17:03,0 days 00:08:09,0 days,2020,4
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255,41.8945,-87.6179,...,2020-04-01,2022-05-24 17:54:13,2020,4,2020-04-01,2022-05-24 18:08:36,0 days 00:14:23,0 days,2020,4
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657,41.9030,-87.6975,...,2020-04-07,2022-05-24 12:50:19,2020,4,2020-04-07,2022-05-24 13:02:31,0 days 00:12:12,0 days,2020,4
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323,41.8902,-87.6262,...,2020-04-18,2022-05-24 10:22:59,2020,4,2020-04-18,2022-05-24 11:15:54,0 days 00:52:55,0 days,2020,4

#### We apply a lamda( also called as anonymous function) to convert the date to weekdays so that we can analyse the data to check variations within a week which is very important for the given task

In [27]:
df["week day"]=df["start_date"].apply(lambda x:x.weekday())
# takes a column and applies weekday function on it through lamba which is an anonymous function
df["week day"].unique() # show only unique values

array([6, 4, 2, 1, 5, 3, 0], dtype=int64)

In [28]:
day_dict={0:"Sunday", 1:"Monday",2:"Tuesday",3:"Wednesday",4:"Thursday",5:"Friday",6:"saturday"}

In [29]:
df["weekday_name"]= df['week day'].apply(lambda y:day_dict[y])

In [30]:
df.isnull().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name     94149
start_station_id       94772
end_station_name      109723
end_station_id        110181
start_lat                  0
start_lng                  0
end_lat                 3857
end_lng                 3857
member_casual              0
distance                   0
start_date                 0
start_time                 0
start_year                 0
start_month                0
end_date                   0
end_time                   0
time_diff                  0
day_diff                   0
end_year                   0
end_month                  0
week day                   0
weekday_name               0
dtype: int64

#### We see that there are no NULL data where it would matter in analysis and thus we can continue

In [31]:
df.duplicated().any()

False

#### We also notice that the dataset does not have any duplicate values which is a good sign !! We are good to go after compeleting our data cleaning process!

In [32]:
df.to_csv("D:\datset_cap\cyclistic_final.csv",index=False)